//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffchainNodeLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetLightningEntities : DbContext
    {
        public AssetLightningEntities()
            : base("name=AssetLightningEntities")
        {
        }
    
    	public AssetLightningEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PreGeneratedOutput> PreGeneratedOutputs { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<ChannelState> ChannelStates { get; set; }
        public virtual DbSet<ChannelCreationInput> ChannelCreationInputs { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
    }
}
